[section]

install.mode = """
sudo install --mode=0755 --directory /etc/apt/keyrings
"""

curl = """
sudo curl https://download.docker.com/linux/ubuntu/gpg docker_ubuntu_gpg.txt
"""

gpg.dearmor = """
sudo gpg --dearmor --output docker.gpg docker_ubuntu_gpg.txt
"""

cp = """
sudo cp docker.gpg /etc/apt/keyrings/docker.gpg
"""

chmod = """
sudo chmod a+r /etc/apt/keyrings/docker.gpg
"""

dpkg.print = """
dpkg --print-architecture
"""

echo.deb.default = """
echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu jammy stable"
"""

echo.deb.tee = """
echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu jammy stable" | \
sudo tee /etc/apt/sources.list.d/docker.list
"""

usermod.append = """
sudo usermod --append --groups docker ubuntu
"""
