[section]

install = """
sudo apt install \
ca-certificates curl gnupg docker-ce docker-ce-cli containerd.io \
docker-buildx-plugin docker-compose-plugin
"""

remove = """
sudo apt remove \
docker.io docker-doc docker-compose podman-docker containerd runc
"""
