#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Module to take out name and index from base name of file."""

from pyspartaproj.context.default.string_context import Strs
from pyspartaproj.context.typed.user_context import BaseName


class BaseNameElements:
    """Class to take out name and index from base name of file."""

    def _initialize_variables(self) -> None:
        self._split_identifier = "_"

    def _get_name_elements(self, name: str, index: int) -> BaseName:
        return {
            "name": name,
            "index": index,
        }

    def _get_index(self, index_text: str) -> int:
        return int(index_text)

    def split_name(self, base_name: str) -> BaseName:
        """Take out name and index from base name of file.

        Define of words.

        File Name: "name_v001a.txt"
        Base Name: "name_v001a"
        Split Identifier: "_"
        Name: "name"
        Index: "v001a"
        Index Number: 1

        e.g., return following data structure
            if you set string "name_v001a" to argument "base_name".

        {
            name: "name"
            index: 1
        }

        Args:
            name (str): Name of file you want to get elements.

        Returns:
            BaseName: Elements generated by name of file.
        """
        identifier: str = self._split_identifier
        names: Strs = base_name.split(identifier)

        return self._get_name_elements(
            identifier.join(names[:-1]), self._get_index(names[-1])
        )

    def __init__(self) -> None:
        """Initialize variable of class."""
        self._initialize_variables()
