[section]

status = """
sudo systemctl status apache2
"""

start = """
sudo systemctl start apache2
"""

enable = """
sudo systemctl enable apache2
"""

is_enabled = """
sudo systemctl is-enabled apache2
"""

restart = """
sudo systemctl restart apache2
"""

daemon_reload = """
sudo systemctl daemon-reload
"""
